name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::637423431574:user/Amministratore
 
    - name: Configure SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
    - name: Deploy nginx into kubernetes cluster
      run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} 'kubectl apply -f "${{ github.action_path }}/nginx-deployment.yaml" '
          
    - name: Expose a service for nginx deployment
      run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} 'kubectl apply -f "${{ github.action_path }}/nginx-service.yaml" '
    
    
